# Generated by Django 4.0.3 on 2022-04-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('variety', models.CharField(max_length=50)),
                ('seed_depth', models.IntegerField()),
                ('seed_spacing', models.IntegerField()),
                ('germination', models.IntegerField()),
                ('plant_spacing', models.IntegerField()),
                ('row_spacing', models.IntegerField()),
                ('days_to_harvest', models.IntegerField()),
                ('sunlight', models.IntegerField()),
                ('indoor_start', models.DateField()),
                ('indoor_stop', models.DateField()),
                ('transplant_start', models.DateField()),
                ('transplant_stop', models.DateField()),
                ('outdoor_start', models.DateField()),
                ('outdoor_stop', models.DateField()),
                ('succession', models.CharField(choices=[('N/A', 'not applicable'), ('7', 're-seed every 7 days'), ('14', 're-seed every 14 days'), ('21', 're-seed every 21 days'), ('30', 're-seed every 30 days')], max_length=50)),
                ('notes', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
    ]
