# Generated by Django 4.0.3 on 2022-04-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_plant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
