# Generated by Django 4.0.3 on 2022-04-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_plant_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='updated_at',
        ),
    ]
