# Generated by Django 4.0.3 on 2022-04-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_plant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
