# Generated by Django 4.0.3 on 2022-04-07 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_plant_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('body', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='notes',
        ),
    ]
