# Generated by Django 4.0.3 on 2022-04-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_note_remove_plant_notes_plant_note'),
    ]

    operations = [

    ]
