# Generated by Django 4.0.3 on 2022-04-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_note_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=300)),
                ('treatment', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='pests',
            field=models.ManyToManyField(to='main_app.pest'),
        ),
    ]
