# Generated by Django 4.0.3 on 2022-04-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_plant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
    ]
