# Generated by Django 4.0.3 on 2022-04-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_plant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='succession',
            field=models.CharField(choices=[('not applicable', 'N/A'), ('re-seed every 7 days', 'ever 7 days'), ('re-seed every 14 days', 'ever 14 days'), ('re-seed every 21 days', 'ever 21 days'), ('re-seed every 30 days', '30')], max_length=50),
        ),
    ]
