# Generated by Django 4.0.3 on 2022-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_plant_succession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(choices=[('Full-Sun', 'Full Sun: minimum 6 hours direct sunlight'), ('Part-Sun', 'Partial Sun: 3-6 hours direct sunlight'), ('Full-Shade', 'Full Shade: less than 3 hours direct sunlight'), ('Part-Shade', 'Partial Shade: 3-6 hours of sunlight, protect from mid-day sunlight')], max_length=80),
        ),
    ]
