# Generated by Django 4.0.3 on 2022-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_plant_sunlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(choices=[('Full Sun: minimum 6 hours direct sunlight', 'Full-Sun'), ('Partial Sun: 3-6 hours direct sunlight', 'Part-Sun'), ('Full Shade: less than 3 hours direct sunlight', 'Full-Shade'), ('Partial Shade: 3-6 hours of sunlight, protect from mid-day sunlight', 'Part-Shade')], max_length=80),
        ),
    ]
