# Generated by Django 4.0.3 on 2022-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_plant_sunlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='seed_depth',
            field=models.CharField(choices=[('Surface, no cover', 'surface'), ('less-than 1/4 inch deep', 'less than 1/4 inch'), ('1/4 inch deep', '1/4 inch'), ('1/2 inch deep', '1/2 inch'), ('2/3 inch deep', '2/3 inch'), ('1 inch deep', '1 inch'), ('more than 1 inch deep', 'more than 1 inch')], max_length=80),
        ),
        migrations.AlterField(
            model_name='plant',
            name='succession',
            field=models.CharField(choices=[('Not Applicable', 'N/A'), ('Re-seed every 7 days', 'ever 7 days'), ('Re-seed every 14 days', 'ever 14 days'), ('Re-seed every 21 days', 'ever 21 days'), ('Re-seed every 30 days', 'every 30 days')], max_length=50),
        ),
    ]
